name: 'dbt_videogames'
version: '1.0.0'
config-version: 2
 
profile: 'dbt_videogames'
 
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
 
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
 
models:
  dbt_videogames:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_utils']