# .dlt/secrets.toml

[destination.snowflake.credentials]
host      = "" # "MyId-Snowflake"
username  = "LOADER_USER"
password  = "" # "MyPassWord"
database  = "DW_VIDEOGAMES"
warehouse = "VIDEOGAMES_WH"
role      = "LOADER_ROLE"